### ISSUE TITLE
Any possibility we can customize the Fields within the embed instead of them being your static format?

### ISSUE THREAD

**Issue by comicallybad** [pxlfl4me/discord-anti-phishing#1]
I like the package, works pretty well and has a lot of links.

One thing I would like the ability to do is change the Fields. Especially the Link field, it would be nice to have it as a spoiler so the link is hidden until clicked on. Just a thought, as well, I personally like to @ mention the user who sent the link, that way I can easily click on their name in the embed and ban them if I feel the need.

Just thought I would throw some suggestions out there.

**Comment by comicallybad** [comment]
As well, if possible, are you willing to add the ability for users to make use of a .then() after the antiPhishing() call? That way if a phishing message is sent, it can be logged to a log channel? I thought this was actually working until I realized it was sending an embed every single time any user sent a message. So possibly return a true or false, if the message was flagged as a phishing link or not.

**Comment by pxlfl4me** [comment]
Hi, thanks for the advice, in the next few days I will put options as you requested

**Comment by pxlfl4me** [comment]
> As well, if possible, are you willing to add the ability for users to make use of a .then() after the antiPhishing() call? That way if a phishing message is sent, it can be logged to a log channel? I thought this was actually working until I realized it was sending an embed every single time any user sent a message. So possibly return a true or false, if the message was flagged as a phishing link or not.

if you have anything else tell me

**Comment by comicallybad** [comment]
```js
const Discord = require('discord.js');
const urlJson = require('./json/url.json');

exports.antiPhishing = async function(message, embed){
    if(!message) return console.error('Specify a first parameter (Discord.Message)');
    if(!embed) return console.error('Specify a second parameter (Discord.MessageEmbed)');
    if(!message.author && !message.content && !message.member) return console.error('Specify a valid (Discord.Message)');
    if(embed.length < 2 && !embed.title) return console.error('Specify a valid (Discord.MessageEmbed)');

    let presente = [];
    for(let i = 0; i < urlJson.domains.length; i++){
        let url = urlJson.domains[i];
        if(message.content.includes(url)){
            presente.push(url);
            break;
        }
    }
        

    if(presente.length == 1){
        message.delete();
        
        embed.addField('Link:', '||' + presente[0] + '||');
        embed.setThumbnail(message.author.displayAvatarURL());

        message.channel.send({embeds: [embed]});

        let res = { message: message, link: presente[0] }
        
        return res;
    }
}
```
I think something like this would work really nicely

**Comment by pxlfl4me** [comment]
> 

Hi, I'm working on it, I'm making sure that I can use a real discord.js wrapper with the return of:
1. Link,
2. User info,
3. Without passing the embed

I will publish it today or tomorrow

**Comment by pxlfl4me** [comment]
I will publish it today or tomorrow

**Comment by pxlfl4me** [comment]
@comicallybad Hi, I updated as I told you, try it and let me know!
uninstall and reinstall the package for have all implementation

**Comment by pxlfl4me** [comment]
uninstall and reinstall the package for have all implementation
